server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: changeMe
    username: changeMe
    password: changeMe
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      snomed:
        cis:
          security: ERROR
      springframework: ERROR
      apache:
        tomcat: ERROR
crowd:
  url: changeMe
  application: changeMe
  password: changeMe
ims:
  urls:
    base: changeMe
    login: /authenticate
    logout: /account/logout
    authenticate: /account
  cookiename: changeMe
